name: codercord
description: A Discord bot for our community server.
version: 1.0.0
homepage: https://github.com/coder/codercord
environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies: 
  logging: ^1.0.2
  nyxx: ^4.5.0
  nyxx_interactions: ^4.5.0
  toml: ^0.13.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
