name: codercord
description: A Discord bot for our community server.
version: 1.0.0
homepage: https://github.com/coder/codercord
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies: 
  logging: ^1.0.2
  nyxx: ^5.1.0
  nyxx_interactions: ^4.5.0
  toml: ^0.14.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
